name: containerised-pos

services:
  database:
    image: postgres:alpine
    container_name: postgres
    restart: on-failure:5
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_DB: point_of_sale
      POSTGRES_PASSWORD: point_of_sale

  admin:
    image: dpage/pgadmin4:8.13.0
    container_name: pgadmin
    restart: on-failure:5
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: turitoyuenan@proton.me
      PGADMIN_DEFAULT_PASSWORD: point_of_sale
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
